public class Constants {
	public static final integer DEFAULT_ROWS = 5;
    public static final string SELECT_ONE = label.Select_One;
    public static final string INVENTORY_LEVEL_LOW = label.Inventory_Level_Low;
    public static final List<Schema.PicklistEntry> PRODUCT_FAMILY = Product2.Family.getDescribe().getPicklistValues();
    public static final string DRAFT_ORDER_STATUS = 'Draft';
    public static final string ACTIVATED_ORDER_STATUS = 'Activated';
    public static final string INVENTORY_ANNOUNCEMENTS = 'Inventory Announcements';
    public static final string ERROR_MESSAGE = 'An error has occurred, please take a screenshot with the URL and send it to IT.';
    public static final ID STANDARD_PRICEBOOK_ID = '01s2w00000AuMp9AAF';
}